spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chat
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

socket:
  chat:
    server:
      port: 10005
      backlog: 128
